{
  "data": [
    {
      "id": 1,
      "name": "Bồn nước inox 700L Ngang - SUS 304",
      "image": "https://www.tdm.vn/image/cache/data/product-3186/ban-ve-bon-inox-700l-toan-my-ngang-1000x1000.jpg",
      "code": "SUS_304_700l",
      "barcode": "8935112200005",
      "type": "product",
      "price": 1200000,
      "standardPrice": 1200000,
      "uomId": 1,
      "description": "Adaptor DC-24V-1,2A (KG09A3, KG10A3) sản phẩm cấu hình ghi các but toán kế toán",
      "saleOk": true,
      "purchaseOk": true,
      "rentOk": false,
      "canBeExpensed": false,
      "qtyAvailable": 11,
      "tracking": "none"
    },
    {
      "id": 2,
      "name": "Acoustic Bloc Screens",
      "image": "https://demo.portcities.vn/web/image/product.template/25/image_1024?unique=7816f19",
      "code": "FURN_6666",
      "barcode": "8934804028125",
      "type": "product",
      "price": 1200000,
      "standardPrice": 1200000,
      "uomId": 1,
      "description": "Adaptor DC-24V-1,2A (KG09A3, KG10A3) sản phẩm cấu hình ghi các but toán kế toán",
      "saleOk": true,
      "purchaseOk": true,
      "rentOk": false,
      "canBeExpensed": false,
      "qtyAvailable": 12,
      "tracking": "none"
    },
    {
      "id": 3,
      "name": "Bolt",
      "image": "https://images.homedepot-static.com/productImages/c31796fc-fdd9-4994-9c5a-97d7ee2b6d4f/svn/everbilt-hex-bolts-80450-64_600.jpg",
      "code": "CONS_89957",
      "barcode": "NV10001",
      "type": "product",
      "price": 1200000,
      "standardPrice": 1200000,
      "uomId": 1,
      "description": "Adaptor DC-24V-1,2A (KG09A3, KG10A3) sản phẩm cấu hình ghi các but toán kế toán",
      "saleOk": true,
      "purchaseOk": true,
      "rentOk": false,
      "canBeExpensed": false,
      "qtyAvailable": 13,
      "tracking": "none"
    },
    {
      "id": 4,
      "name": "Bàn làm việc chân chữ Z",
      "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKCNThunJH6cfqRknaXVNd16FlMVXOx6xNEHOK_TSrS1asz2w&usqp=CAc",
      "code": "BLVZ",
      "barcode": "NV10001",
      "type": "product",
      "price": 1200000,
      "standardPrice": 1200000,
      "uomId": 1,
      "description": "Adaptor DC-24V-1,2A (KG09A3, KG10A3) sản phẩm cấu hình ghi các but toán kế toán",
      "saleOk": true,
      "purchaseOk": true,
      "rentOk": false,
      "canBeExpensed": false,
      "qtyAvailable": 14,
      "tracking": "none"
    }
  ]
}
